@extends('layouts.app')
@section('title','فحص الجودة '.$order->production_number)
@section('page-title','فحص الجودة')
@section('content')
<div class="page-header"><div><h1 class="page-heading">{{ $order->production_number }}</h1><p class="page-subheading">{{ $order->product?->name_ar ?: $order->product?->name }} — {{ $order->location?->name }}</p></div><a class="btn btn-ghost" href="{{ route('quality-control.index') }}">رجوع</a></div>
<div class="stats-grid" style="grid-template-columns:repeat(4,1fr);margin-bottom:1rem"><div class="stat-card"><div class="stat-info"><div class="stat-value">{{ number_format((float)$order->planned_output_quantity,3) }}</div><div class="stat-label">المخطط</div></div></div><div class="stat-card"><div class="stat-info"><div class="stat-value">{{ number_format((float)$order->actual_output_quantity,3) }}</div><div class="stat-label">الناتج الفعلي</div></div></div><div class="stat-card"><div class="stat-info"><div class="stat-value">₪ {{ number_format((float)$order->actual_total_cost,2) }}</div><div class="stat-label">تكلفة الدفعة</div></div></div><div class="stat-card"><div class="stat-info"><div class="stat-value">₪ {{ number_format((float)$order->actual_unit_cost,4) }}</div><div class="stat-label">تكلفة الوحدة</div></div></div></div>
<div class="card" style="margin-bottom:1rem"><div class="card-header"><span class="card-title">مراجعة الاستهلاك</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>المكون</th><th>المخطط</th><th>الفعلي</th><th>التكلفة الفعلية</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product?->name_ar ?: $item->product?->name }}</td><td>{{ number_format((float)$item->planned_quantity,4) }}</td><td>{{ number_format((float)$item->actual_quantity,4) }}</td><td>₪ {{ number_format((float)$item->actual_cost,2) }}</td></tr>@endforeach</tbody></table></div></div>
@can('quality_control.inspect')
<div class="card"><div class="card-header"><span class="card-title">قرار الجودة</span></div><div class="card-body"><div class="form-grid" style="margin-bottom:1rem"><div class="form-group"><label class="form-label">درجة الحرارة / القياس 1</label><input class="form-input qc-measure" data-key="temperature"></div><div class="form-group"><label class="form-label">الوزن / القياس 2</label><input class="form-input qc-measure" data-key="weight"></div><div class="form-group" style="grid-column:1/-1"><label class="form-label">ملاحظات الفحص</label><textarea id="qc-notes" class="form-input" rows="3"></textarea></div></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem">
<form id="approve-form" method="POST" action="{{ route('quality-control.approve',$order) }}">@csrf<div class="qc-hidden"></div><input type="hidden" name="notes"><button class="btn btn-gold" style="width:100%" onclick="return prepareQc(this.form,false)">اعتماد الجودة وإدخال المخزون</button></form>
<form id="reject-form" method="POST" action="{{ route('quality-control.reject',$order) }}">@csrf<div class="qc-hidden"></div><input type="hidden" name="notes"><input class="form-input" name="rejection_reason" placeholder="سبب الرفض مطلوب" required style="margin-bottom:.5rem"><button class="btn btn-outline" style="width:100%" onclick="return prepareQc(this.form,true)">رفض الناتج</button></form>
</div></div></div>
@push('scripts')<script>function prepareQc(form,reject){form.querySelector('input[name="notes"]').value=document.getElementById('qc-notes').value;const box=form.querySelector('.qc-hidden');box.innerHTML='';document.querySelectorAll('.qc-measure').forEach(el=>{if(!el.value)return;const input=document.createElement('input');input.type='hidden';input.name=`measurements[${el.dataset.key}]`;input.value=el.value;box.appendChild(input);});return confirm(reject?'سيتم رفض الناتج ولن يدخل المخزون. متابعة؟':'سيتم اعتماد الجودة وإدخال الناتج إلى المخزون. متابعة؟');}</script>@endpush
@endcan
</div>
@endsection
