@php $editing = isset($variant); $selectedValues = old('attribute_value_ids', $editing ? $variant->attributeValues->pluck('id')->all() : []); @endphp
@if($errors->any())<div style="margin-bottom:1rem;padding:1rem;background:#fef2f2;border:1px solid #fecaca;border-radius:10px;color:#991b1b"><ul style="margin:0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div style="display:grid;gap:1rem">
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem"><div class="form-group"><label class="form-label">اسم المتغير (إنجليزي)</label><input name="name" class="form-input" value="{{ old('name',$variant->name ?? '') }}"></div><div class="form-group"><label class="form-label">اسم المتغير (عربي)</label><input name="name_ar" class="form-input" value="{{ old('name_ar',$variant->name_ar ?? '') }}"></div></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem"><div class="form-group"><label class="form-label">المقاس</label><select name="size_id" class="form-select"><option value="">بدون مقاس</option>@foreach($sizes as $size)<option value="{{ $size->id }}" @selected((string)old('size_id',$variant->size_id ?? '') === (string)$size->id)>{{ $size->displayName() }}</option>@endforeach</select></div><div class="form-group"><label class="form-label">اللون</label><select name="color_id" class="form-select"><option value="">بدون لون</option>@foreach($colors as $color)<option value="{{ $color->id }}" @selected((string)old('color_id',$variant->color_id ?? '') === (string)$color->id)>{{ $color->displayName() }}</option>@endforeach</select></div></div>
<div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:1rem"><div class="form-group"><label class="form-label">SKU</label><input name="sku" class="form-input" dir="ltr" value="{{ old('sku',$variant->sku ?? '') }}" placeholder="اتركه فارغًا للتوليد"></div><div class="form-group"><label class="form-label">EAN-13</label><input name="barcode" class="form-input" dir="ltr" value="{{ old('barcode',$variant->barcode ?? '') }}" placeholder="اتركه فارغًا للتوليد"></div><div class="form-group"><label class="form-label">سعر المتغير</label><input name="selling_price" type="number" min="0" step="0.01" class="form-input" value="{{ old('selling_price',$variant->selling_price ?? '') }}" placeholder="فارغ = سعر المنتج"></div></div>
@if($attributes->isNotEmpty())<div class="card" style="box-shadow:none"><div class="card-header"><span class="card-title">خصائص إضافية</span></div><div class="card-body" style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem">@foreach($attributes as $attribute)<div><strong style="display:block;margin-bottom:.4rem">{{ $attribute->displayName() }}</strong>@foreach($attribute->values as $value)<label style="display:flex;gap:.4rem;align-items:center;margin:.25rem 0"><input type="checkbox" name="attribute_value_ids[]" value="{{ $value->id }}" @checked(in_array($value->id,$selectedValues))>{{ $value->displayName() }}</label>@endforeach</div>@endforeach</div></div>@endif
<div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem"><div class="form-group"><label class="form-label">صورة المتغير</label><input type="file" name="image" class="form-input" accept="image/*"></div><div class="form-group"><label class="form-label">الترتيب</label><input name="sort_order" type="number" min="0" class="form-input" value="{{ old('sort_order',$variant->sort_order ?? 0) }}"></div></div>
<div style="display:flex;gap:1.2rem;flex-wrap:wrap"><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$variant->is_active ?? true))> فعال</label><label><input type="checkbox" name="is_default" value="1" @checked(old('is_default',$variant->is_default ?? false))> المتغير الافتراضي</label></div>
</div>
